analyze:
  image: cirrusci/flutter:stable
  stage: check
  script:
    - flutter pub get
    - dartanalyzer . --fatal-infos --fatal-warnings


format:
  image: google/dart:latest
  stage: check
  script:
    - dartfmt --fix -n --set-exit-if-changed .