workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID

stages:
  - check
  - test
  - build

analyze:
  image: cirrusci/flutter:stable
  stage: check
  script:
    - flutter pub get
    - flutter pub run build_runner build
    - touch .env # We add an empty .env so the analyzer is happy.
    - dart analyze . --fatal-infos --fatal-warnings

format:
  image: cirrusci/flutter:stable
  stage: check
  script:
    # We don't generate any code, because we don't want to check that anyway.
    - dart format -o none --fix --set-exit-if-changed .

test:
  image: cirrusci/flutter:stable
  stage: test
  script:
    - cp .env.example .env
    - flutter pub get
    - flutter pub run build_runner build
    - flutter pub global activate junitreport
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter test --machine | tojunit --output report.xml
  artifacts:
    reports:
      junit: report.xml

trigger codemagic build:
  image: curlimages/curl:latest
  stage: build
  script:
    - >-
      curl -H "Content-Type: application/json" -H "x-auth-token: $CODEMAGIC_API_TOKEN" 
      \--data '{"appId": "'"$CODEMAGIC_APP_ID"'","workflowId": "'"$CODEMAGIC_MERGE_REQUESTS_WORKFLOW_ID"'","branch": "'"$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"'","environment": {"variables": {"GITLAB_MERGE_REQUEST_IID": "'"$CI_MERGE_REQUEST_IID"'"}}}' https://api.codemagic.io/builds
