workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID

stages:
  - build and test

build & test:
  image: cirrusci/flutter:latest
  stage: build and test
  rules:
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "detached"'
      variables:
        CODEMAGIC_WORKFLOW: "merge-requests"
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"'
      variables:
        CODEMAGIC_WORKFLOW: "merge-requests"
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      variables:
        CODEMAGIC_WORKFLOW: "main"
  artifacts:
    when: always
    reports:
      junit: "test_results/**/test_result_*.xml"
  before_script:
    - dart ./utils/ci/gitlab/remove_build_url.dart
    - apt-get update && apt-get -y -qq install python3
    - dart pub get
  script:
    - dart ./utils/ci/gitlab/build_via_codemagic.dart
