workflow:
  rules:
     - if: $CI_MERGE_REQUEST_IID

stages:
  - check
  - test
  - build

analyze:
  image: cirrusci/flutter:1.20.1
  stage: check
  script:
    - flutter pub get
    # This next line is necessary because the analyzer's exclude functionality is currently
    # not working. See here for more: https://github.com/dart-lang/sdk/issues/25551
    # If any analysis errors occur in the generated messages file, there probably
    # needs to be another rule to be ignored added to the comment below.
    - >-
      echo "// ignore_for_file: unused_element, lines_longer_than_80_chars,
      annotate_overrides, camel_case_types, prefer_single_quotes, unused_field,
      avoid_equals_and_hash_code_on_mutable_classes"
      | tee -a lib/app/resources/messages*.i18n.dart
      lib/data/repositories/services/*.chopper.dart
      lib/data/repositories/db/*.g.dart
    - dartanalyzer . --fatal-infos --fatal-warnings

format:
  image: google/dart:latest
  stage: check
  script:
    - >-
      dartfmt $(find . -type f
      \( -iname "*.dart" ! -path "./lib/app/resources/messages*.i18n.dart" \))
      --fix -n --set-exit-if-changed

test:
  image: cirrusci/flutter:1.20.1
  stage: test
  script:
    - cp .env.example .env
    - flutter pub get
    - flutter pub global activate junitreport
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter test --machine | tojunit --output report.xml
  artifacts:
    reports:
      junit: report.xml

trigger codemagic build:
  image: cirrusci/flutter:1.20.1
  stage: build
  script:
    - >-
      curl -H "Content-Type: application/json" -H "x-auth-token: $CODEMAGIC_API_TOKEN" 
      \--data '{"appId": "'"$CODEMAGIC_APP_ID"'","workflowId": "'"$CODEMAGIC_MERGE_REQUESTS_WORKFLOW_ID"'","branch": "'"$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"'","environment": {"variables": {"GITLAB_MERGE_REQUEST_IID": "'"$CI_MERGE_REQUEST_IID"'"}}}' https://api.codemagic.io/builds
