stages:
  - check

analyze:
  image: cirrusci/flutter:stable
  stage: check
  script:
    - flutter pub get
    - dartanalyzer . --fatal-infos --fatal-warnings

format:
  image: google/dart:latest
  stage: check
  script:
    - >-
      dartfmt $(find . -type f
      \( -iname "*.dart" ! -path "./lib/app/resources/messages*.i18n.dart" \))
      --fix -n --set-exit-if-changed