name: vialer
description: >-
  Mobile app that serves as both a VoIP client
  and a management tool for accounts on the VoIPGRID platform.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # TODO: Use pub dependency.
  voip_flutter_integration:
    path: voip_flutter_integration

  flutter_bloc: ^6.1.0

  pedantic: ^1.9.0

  provider: ^4.0.2

  equatable: ^1.0.2

  chopper: ^3.0.1+1

  shared_preferences: ^0.5.12+4

  flutter_svg: ^0.18.0

  android_intent: ^0.3.5
  permission_handler: ^5.0.1+1

  url_launcher: ^5.4.1

  contacts_service: ^0.4.6

  characters: ^1.0.0
  diacritic: ^0.1.1

  flutter_widgets: ^0.1.11

  i18n: ^1.2.0
  intl: ^0.16.0

  flutter_dotenv: ^2.1.0

  sentry: ^3.0.1
  flutter_segment: ^3.0.0

  device_info: ^1.0.0
  package_info: '>=0.4.0+18 <2.0.0'

  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0

  path_provider: ^1.6.5
  path: ^1.6.4

  timezone: ^0.5.6

  logging: ^0.11.4

  libphonenumber: ^1.0.1

  get_it: ^5.0.1

  dartx: ^0.5.0

  connectivity: ^2.0.2

  webview_flutter: ^1.0.5

  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.2.0

  build_runner: ^1.10.0
  chopper_generator: ^3.0.1+1

  moor_generator: ^3.3.1

  json_serializable: ^3.5.0

  flutter_launcher_icons: ^0.8.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/background_cloud.svg
    - assets/survey/help.png
    - assets/survey/yay.png

  fonts:
    - family: 'VialerSans'
      fonts:
        - asset: assets/vialer_sans.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
